apiVersion: v1 # v1, v1, apps/v1, apps/v1
kind: Pod # Pod, Service, ReplicaSet, Deployment
metadata:
  name: myapp-pod
  labels:
    app: myapp
    type: front-end
spec:
  containers:
    - name: nginx-container
      image: nginx